/* Generated by Phoenix Tuner X */
package frc.robot.subsystems.LED;

import static edu.wpi.first.units.Units.*;

import com.ctre.phoenix6.CANBus;
import com.ctre.phoenix6.controls.ColorFlowAnimation;
import com.ctre.phoenix6.controls.FireAnimation;
import com.ctre.phoenix6.controls.RainbowAnimation;
import com.ctre.phoenix6.hardware.CANdle;
import com.ctre.phoenix6.signals.AnimationDirectionValue;
import com.ctre.phoenix6.signals.RGBWColor;
import edu.wpi.first.wpilibj2.command.Command;
import edu.wpi.first.wpilibj2.command.Commands;
import edu.wpi.first.wpilibj2.command.SubsystemBase;

/** Subsystem that controls an addressable LED strip using a CANdle. */
public class LEDSubsystem extends SubsystemBase {
  private final CANBus kCANBus = new CANBus("Superstructure");
  private final CANdle m_candle = new CANdle(1, kCANBus);

  // Fire animation for testing
  private final FireAnimation m_testAnimation =
      new FireAnimation(0, 68)
          .withSlot(0)
          .withBrightness(0.215)
          .withDirection(AnimationDirectionValue.Forward)
          .withSparking(1)
          .withCooling(0.331)
          .withFrameRate(Hertz.of(38.22));

  // Off animation - zero brightness to turn off LEDs
  private final FireAnimation m_offAnimation =
      new FireAnimation(0, 68)
          .withSlot(0)
          .withBrightness(0)
          .withDirection(AnimationDirectionValue.Forward)
          .withSparking(0)
          .withCooling(0)
          .withFrameRate(Hertz.of(1));

  // Robot State Animations with Colors
  // All animations use slot 0 so setting a new one automatically replaces the previous.

  // Green - Stowed/Idle state
  private final ColorFlowAnimation m_stowedAnimation =
      new ColorFlowAnimation(0, 68)
          .withSlot(0)
          .withColor(new RGBWColor(0, 255, 0, 0)) // Green
          .withDirection(AnimationDirectionValue.Forward)
          .withFrameRate(Hertz.of(15));

  // Blue - Intaking
  private final ColorFlowAnimation m_intakingAnimation =
      new ColorFlowAnimation(0, 68)
          .withSlot(0)
          .withColor(new RGBWColor(0, 0, 255, 0)) // Blue
          .withDirection(AnimationDirectionValue.Forward)
          .withFrameRate(Hertz.of(30));

  // Yellow - Has game piece / Holding
  private final ColorFlowAnimation m_holdingAnimation =
      new ColorFlowAnimation(0, 68)
          .withSlot(0)
          .withColor(new RGBWColor(255, 255, 0, 0)) // Yellow
          .withDirection(AnimationDirectionValue.Forward)
          .withFrameRate(Hertz.of(20));

  // Orange - Preparing to shoot / Aiming
  private final ColorFlowAnimation m_aimingAnimation =
      new ColorFlowAnimation(0, 68)
          .withSlot(0)
          .withColor(new RGBWColor(255, 165, 0, 0)) // Orange
          .withDirection(AnimationDirectionValue.Forward)
          .withFrameRate(Hertz.of(35));

  // Red - Shooting
  private final ColorFlowAnimation m_shootingAnimation =
      new ColorFlowAnimation(0, 68)
          .withSlot(0)
          .withColor(new RGBWColor(255, 0, 0, 0)) // Red
          .withDirection(AnimationDirectionValue.Forward)
          .withFrameRate(Hertz.of(40));

  // Purple - Climbing
  private final ColorFlowAnimation m_climbingAnimation =
      new ColorFlowAnimation(0, 68)
          .withSlot(0)
          .withColor(new RGBWColor(128, 0, 255, 0)) // Purple
          .withDirection(AnimationDirectionValue.Forward)
          .withFrameRate(Hertz.of(20));

  // Rainbow - All good / Teleop
  private final RainbowAnimation m_rainbowAnimation =
      new RainbowAnimation(0, 68)
          .withSlot(0)
          .withBrightness(0.8)
          .withDirection(AnimationDirectionValue.Forward)
          .withFrameRate(Hertz.of(25));

  // White - Error/Disabled
  private final ColorFlowAnimation m_errorAnimation =
      new ColorFlowAnimation(0, 68)
          .withSlot(0)
          .withColor(new RGBWColor(255, 255, 255, 0)) // White
          .withDirection(AnimationDirectionValue.Forward)
          .withFrameRate(Hertz.of(10));

  public LEDSubsystem() {
    // No default command - LEDs controlled manually
  }

  // Direct setter methods - no Commands needed

  /** Show test fire animation */
  public void setTest() {
    m_candle.setControl(m_testAnimation);
  }

  /** Turn off all LEDs */
  public void setOff() {
    m_candle.setControl(m_offAnimation);
  }

  /** Show stowed/idle state - green color flow */
  public void setStowed() {
    m_candle.setControl(m_stowedAnimation);
  }

  /** Show intaking state - blue color flow */
  public void setIntaking() {
    m_candle.setControl(m_intakingAnimation);
  }

  /** Show holding game piece state - yellow color flow */
  public void setHolding() {
    m_candle.setControl(m_holdingAnimation);
  }

  /** Show aiming state - orange color flow */
  public void setAiming() {
    m_candle.setControl(m_aimingAnimation);
  }

  /** Show shooting state - red color flow */
  public void setShooting() {
    m_candle.setControl(m_shootingAnimation);
  }

  /** Show climbing state - purple color flow */
  public void setClimbing() {
    m_candle.setControl(m_climbingAnimation);
  }

  /** Show rainbow animation - teleop enabled */
  public void setRainbow() {
    m_candle.setControl(m_rainbowAnimation);
  }

  /** Show error/disabled state - white color flow */
  public void setError() {
    m_candle.setControl(m_errorAnimation);
  }

  // Command factory methods for button bindings

  /** Command to show test animation */
  public Command testAnimation() {
    return Commands.runOnce(this::setTest);
  }

  /** Command to turn off LEDs */
  public Command off() {
    return Commands.runOnce(this::setOff);
  }
}
